apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  # Aeon
  - name: aeon-api-image
    newName: lucascantarelli/aeon-api
    newTag: 0.1.0-snapshot

resources:
- ../../base

patches:
  # Base
  - path: ./ingress.yaml
    target:
      kind: Ingress
      name: development-ingress

configMapGenerator:
  # Aeon
  - name: aeon-config
    behavior: merge
    literals:
      - TES=taaaaa