apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app.kubernetes.io/developer: dolorestec
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    $DOCKER_TOKEN