apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Ingress Base
  - ingress.yaml
  # Docker Registry
  - ./secrets/docker-registry-secret.yaml
  # AEON APP
  - ./aeon/aeon-api-deployment.yaml
  - ./aeon/aeon-api-service.yaml
  - ./config/aeon-config.yaml
  - ./secrets/aeon-secret.yaml