apiVersion: v1
kind: Service
metadata:
  name: aeon-api
  labels:
    app.kubernetes.io/name: aeon-api
    app.kubernetes.io/developer: dolorestec
spec:
  selector:
    app.kubernetes.io/name: aeon-api
  type: ClusterIP
  ports:
  - port: 9000